### PR TITLE
Revert "Add handling for WordPress.com files"

### PR DESCRIPTION
**Pull request by ockham**
Reverts Automattic/photon.js#10

This was giving us CORS issues in Calypso, so we had to revert the PR that bumped the `photon.js` version there (https://github.com/Automattic/wp-calypso/pull/30075). I'm assuming we should also revert here.

### CODE REVIEW

**Comment by sirreal** [comment]
Let's wait on this, it's possible that the change from #10 is still valid depending on how some discussions turn out. I deprecated the 3.0.0 release which contained this so it shouldn't be used via npm.

**Comment by ockham** [comment]
> I deprecated the 3.0.0 release which contained this so it shouldn't be used via npm.

Ah great, right. So we were in that 24 hrs period during which that was possible? Nice.

**Comment by sirreal** [comment]
I believe the 24 hour window is for unpublish. I deprecated, meaning the package could be used, but is not dist-tagged as `latest` and will warn on install if that version is used.

**Comment by sirreal** [comment]
No need to revert, this is OK in the Calypso monorepo where the source now lives.

**Pull request closed without merging**
